### ISSUE TITLE
seg_mask is not computed correctly

### ISSUE THREAD

**Issue by lorsanta** [coastalcph/trldc#1]
The computation of seg_mask relies on the fact that the sum of a segment composed of only pad token ids is equal to zero.
https://github.com/coastalcph/trldc/blob/b843576875654bc887e904777ecc4a0dc3091ba5/dainlp/models/cls/hierarchical.py#L59

But with RoBERTa this is not true since by default `pad_token_id = 1`. ([source](https://huggingface.co/transformers/v4.10.1/model_doc/roberta.html#robertaconfig))

It would be better to compute `seg_mask` using `attention_mask` instead of `input_ids`.

**Comment by dainlp** [comment]
thank you for spotting this, i have fixed it
